- name: Install multi python packages with version specifiers
  hosts: all_nodes
  become: yes
  become_user: root
  tasks:
    - name: Install env needed packages
      pip:
        name:
          - numpy
          - requests
          - beautifulsoup4
        executable: pip
